apiVersion: v1
kind: Service
metadata:
  name: deepiot-frontend
  namespace: deepiot
spec:
  type: ClusterIP
  ports:
  - name: port80
    port: 80
    targetPort: 80
  selector:
    app: deepiot-frontend